### ISSUE TITLE
What is the easiest way to change the default mode to Dark by default?

### ISSUE THREAD

**Issue by jsappme** [antfu/vitesse#110]
What is the easiest way to change the default mode to Dark by default?

**Comment by antfu** [comment]
Sorry what do you mean? I kinda suggest you asking questions in Vue or Vite's discord server instead.

**Comment by jsappme** [comment]
By default, the mode is Light, I was trying to change it to Dark by default.

**Comment by antfu** [comment]
Just like how you would do with HTML and CSS? Please use the forum or discord to ask questions.

**Comment by vintprox** [comment]
I think the author meant to find a way for changing default color scheme through **vueuse** utility. My only concern with it is, while one can just put `isDark.value = true` in [`dark.ts`](https://github.com/antfu/vitesse/blob/master/src/logic/dark.ts), it writes into storage and creates visual latency. To clarify:
- this approach doesn't comply with GDPR, since we write `vueuse-color-scheme` key-value pair into LocalStorage prematurely and for such little cause as showing dark theme by default to the user;
- difference in themes and timing of the switch causes a white flash when opening the app in a new tab.

There may be some internal fix to allow the dark color scheme by default, which eliminates listed problems.

**Comment by antfu** [comment]
`<html class="dark">` and remove the `dark.ts` would do, or you can remove all the css and logic, then write your own - it's just a starter template after all.

**Comment by vintprox** [comment]
> `<html class="dark">` and remove the `dark.ts` would do, or you can remove all the css and logic, then write your own - it's just a starter template after all.

I tried that and still, **vueuse** automatically removes `dark` class from `html` element.

**Comment by antfu** [comment]
as I said, if you don't want the ability to toggle the theme, you can remove the `useDark` usage so it won't mess up with your settings.

**Comment by vintprox** [comment]
> as I said, if you don't want the ability to toggle the theme, you can remove the `useDark` usage so it won't mess up with your settings.

Alright, completely erased any usages of `useDark` and now it doesn't mess with storage. I'll address the issue to [vueuse](https://github.com/vueuse/vueuse). Thanks!
