### ISSUE TITLE
Incorrect pages generated with layout plugin

### ISSUE THREAD

**Issue by anishdcruz** [antfu/vitesse#119]
With `vite-plugin-vue-layouts`
<img width="251" alt="Screenshot 2021-05-13 at 9 09 53 PM" src="https://user-images.githubusercontent.com/2182620/118175645-ae432d00-b430-11eb-838d-40c1dc7749d6.png">

Without `vite-plugin-vue-layouts`
<img width="268" alt="Screenshot 2021-05-13 at 9 09 58 PM" src="https://user-images.githubusercontent.com/2182620/118175655-b1d6b400-b430-11eb-857b-2e670a9a46d5.png">

Vite-SSG plugin example
<img width="278" alt="Screenshot 2021-05-13 at 9 18 47 PM" src="https://user-images.githubusercontent.com/2182620/118175787-d92d8100-b430-11eb-81e9-a2f35ff6ad6c.png">

With the layout plugin, extra folders are created and the content is same as index.html

<img width="1792" alt="Screenshot 2021-05-13 at 9 25 18 PM" src="https://user-images.githubusercontent.com/2182620/118176615-ee56df80-b431-11eb-842d-3279bd364729.png">

When i visit /readme, i get the content from readme folder instead of correct readme.html

Please let me know if this the expected behaviour or a bug.

I am big fan of your open source work :)
Thank you!

**Comment by ctholho** [comment]
Are you seeing this?
<img width="927" alt="Screenshot" src="https://user-images.githubusercontent.com/28910105/118477776-5ac22f00-b70f-11eb-9580-12f55df067e3.png">

If yes, you are not using a server environment. You need to run `pnpm preview` on your local machine.

If you use `pnpm build && pnpm preview` or deploy to server and visit `localhost:5000/readme/` (with or without trailing slash – shouldn't matter) you should see the content of `src/pages/readme.vue` wrapped by the layout `src/layouts/default.vue`. In the `dist/` directory, that is the file corresponding to `dist/readme.html`.

The file `dist/readme/readme.html` on the other hand is generated with the content of `[...all].vue` and it's corresponding layout `src/layouts/404.vue`. Because it is the fallback for cases when users visit `localhost:5000/readme/does-not-exist`.

**Comment by hannoeru** [comment]
@ctholho that is because vite-plugin-vue-layouts didn't replace route path when wrap with layout components in generated routes.

https://github.com/JohnCampionJr/vite-plugin-vue-layouts/blob/703ab791b17572806060d890c7eb12d58c41b0cb/src/RouteLayout.ts#L12

Also looks like it ignored `route.name`.

**Comment by ctholho** [comment]
Thanks for looking into this @hannoeru.

I had expected a nested router view that has a path starting with `'/'` would just be displayed at root level. Without anything fancy happening to the router. As per the [vue router docs#nested routes](https://next.router.vuejs.org/guide/essentials/nested-routes.html):

> Note that nested paths that start with / will be treated as a root path. This allows you to leverage the component nesting without having to use a nested URL.

So my assumption was, if a root level route had the same path as a children route (with a prefixed `/`). It should be displayed at the same path, and therefore also be _rendered_ at the same path.

Replacing the path of children to an empty string `''` (also proposed in the router docs) is possible but always creates a `dist/.html` file that's identical with `dist/index.html` (if building with `vite-ssg`)

Could the culprit be this? [vite-SSG /utils.ts#L25](https://github.com/antfu/vite-ssg/blob/9a503416a8c69be5916d08b1fe81e605f4ba830f/src/node/utils.ts#L25)

That being said: Are there any issues for website visitors that result in missing, wrongly displayed pages? (I'm asking to know if this issue should be high priority for `vite-plugin-vue-layouts`)

Regarding `route.name`: Linking to a named routes _should_ still work because vue-router looks for names in `children`.

**Comment by hannoeru** [comment]
Just fixed empty string problem with vite-ssg, can you try it?

**Comment by ctholho** [comment]
Works great.

**Comment by ctholho** [comment]
Hmm. I wonder if it is a good idea if we change [Line 31](https://github.com/antfu/vite-ssg/blob/926094ec43f6f3a3ebe0562c212553620707ad8a/src/node/utils.ts#L31)
```
getPaths(route.children, route.path)
```
to something like
```
getPaths(route.children, route.path || prefix)
```

That would fix the missing route problem I keep having with the `vite-plugin-vue-layouts/examples/ssg` and the PR I submitted.

... But it still feels like a crutch.
