### ISSUE TITLE
Is it possible to use: <component v-bind:is="'my-component-name'">

### ISSUE THREAD

**Issue by frck006** [antfu/vitesse#212]
Hi,

I don't know how to use <component **v-bind:is=**"my-component-name"> with vitesse.

For example, if I use `<component v-bind:is="'n-textfield'" v-bind:props="$props">`

DOM contents: 
![image](https://user-images.githubusercontent.com/10244725/137631005-727c9d73-23aa-4110-ba2a-1f304f240b1b.png)

=> NTextfield is not rendered.

Do you know how to do this ?

**Comment by userquin** [comment]
On vue 3 you should use `v-bind="props"`, vue 3 doesn't separate events, attrs and props anymore

**Comment by userquin** [comment]
I think you cannot pass data to this built-in component: https://v3.vuejs.org/api/built-in-components.html#component

**Comment by userquin** [comment]
You can define a component with inherit attrs to false, then on render function render the desired component passibg props.

For example for inherit attrs: https://github.com/userquin/vite-ssg/blob/feat/i18n-ssg-router/src/client/components/I18nRouterLink.ts#L6

**Comment by frck006** [comment]
Hum, I tried to add NTextfield in the template like this.
If I use "<NTextfield>", it works
If I use "<component :is>", it doesn't :(
(I try with NTextfield and n-textfield)
![image](https://user-images.githubusercontent.com/10244725/137638997-8e0df2dc-ed7e-4908-94d2-1f9fcbafd46e.png)

**Comment by userquin** [comment]
The problem is how to resolve the component and how it is registered.

Using script setup, all components imported and used on the template will be registered.

Since you are using the built in component for dynamic components you need to register all components used with it. If you import date component the script setup will no register it sibce it is not being used on the template.

So you have 2 options:
- use defineComponent adding all components on components and then add logic on render funtion to render ine of the components  or
- use option api adding all components on components using the data entry to declare the `is`  value for the built in component

**Comment by userquin** [comment]
If you need to pass props, just import all components, then instead using component just use v-if, v-else-if and v-else in each one with your logic.

If you are using 1 component it makes no sense using it this way.
