### ISSUE TITLE
Failed to load source map 

### ISSUE THREAD

**Issue by Ragura** [antfu/vitesse#281]
First of all, thanks again for the amazing template. Not only is it handy to quickly prototype an idea, but it has also taught me a lot about Vite and typescript configs that would have been hard to figure out by myself.

I'm encountering one issue where, after a simple clone of the template, the browser gives the following error:
```DevTools failed to load source map: Could not load content for http://localhost:3000/@vite/client.mjs.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE```

It doesn't seem to have an impact on the functionality of the template, but something must be causing it.
I know you have a million other awesome projects you're working on, so this is probably not a priority for you. So, if you don't have the time, perhaps you or anyone else could give some information on how to debug an error like this and we could try to fix it in a pull request?

I've tried removing some plugins and also the optimizedeps option of Vite, but that didn't seem to fix it.

**Comment by GavinXue** [comment]
I found that It is caused by @intlify/vite-plugin-vue-i18n version 3.2.1, as you can find the issue here: https://github.com/intlify/bundle-tools/issues/1#issuecomment-1013841297 
if someone worry about it, you can downgrade the plugin to version 3.1.1 (@intlify/vite-plugin-vue-i18n) to fix this warning. and then wait the plugin to upgrade.

**Comment by Ragura** [comment]
This does indeed fix it! Thanks for the heads up. Here's hoping the problem will get fixed eventually on their side.
