### ISSUE TITLE
unique app ids cause vite-ssg to fail under build

### ISSUE THREAD

**Issue by QuixoticGitHub** [antfu/vitesse#300]
How to replicate:  

**change in index.html:**
`<div id="app" ></div>` to `<div id='someuniqueappid' ></div>`

**Set the new rootContainer in main.ts:**

```
export const createApp = ViteSSG(
  App,
  { routes, base: import.meta.env.BASE_URL },
  (ctx) => {
    // install all modules under `modules/`
    Object.values(import.meta.globEager('./modules/*.ts')).forEach(i => i.install?.(ctx))
  },
  { rootContainer: '#someuniqueappid'}
)
```

**pnpm run build** should now result in 
[vite-ssg] An internal error occurred

Error: Could not find a tag with id="app" to replace it with server-side rendered HTML at renderHTML ...

**Comment by userquin** [comment]
@QuixoticGitHub I've it working, the problem is that the client and the build configuration are not connected; we use `ViteSSG({..., { rootContainer: 'xxx' }})` on the client side and we need to include the SSG data (state) t on build and we need to access the correct container.

I'll add another entry on `ssgOptions` called `rootContainerId` to include the corresponding id, on the client side is a query selector or just adom  `Element`, so both entries should be in sync; following with previous `ViteSSG` example, you will need to add on `ssgOptions` the option: `rootContainerId: 'xxx'`.

PR on `vite-ssg` in a few minutes.
