### ISSUE TITLE
How to add icons from a variable

### ISSUE THREAD

**Issue by rashidpathiyil** [antfu/vitesse#78]
How to add when icon name is inside a variable?

```
const icon="carbon-user" 

<carbon-user class="text-5xl" />

```

This is not working on Vitesse
`<span class="iconify" data-icon="carbon:center-circle" data-inline="false"></span>`

**Comment by SamuelAlev** [comment]
You should be able to use `<Component :is="icon" />` ([docs here](https://v3.vuejs.org/guide/render-function.html#component-and-is))

**Comment by antfu** [comment]
@rashidpathiyil The syntax you provide requires Iconify runtime, where you can use it with `purge-icons` installed. https://github.com/antfu/purge-icons/tree/main/packages/vite-plugin-purge-icons Or just simply import `@iconify/iconify` if you don't need to bundle them.

Otherwise, @SamuelAlev already offered the solution.

**Comment by rafalolszewski94** [comment]
now how to do you use icons from variable using unocss icons?
